/*
 * Author: David Slovikosky
 * Mod: Afraid of the Dark
 * Ideas and Textures: Michael Albertson
 */
package com.DavidM1A2.AfraidOfTheDark.common.entities.WereWolf;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

// Werewolf model by Michael Albertson
public class ModelWereWolf extends ModelBase
{
	// fields
	ModelRenderer RFoot;
	ModelRenderer LFoot;
	ModelRenderer RFootRToe;
	ModelRenderer RFootLToe;
	ModelRenderer RFootRToeA;
	ModelRenderer RFootLToeA;
	ModelRenderer RFootMToe;
	ModelRenderer RFootMToeA;
	ModelRenderer LFootRToe;
	ModelRenderer LFootRToeA;
	ModelRenderer LFootMToe;
	ModelRenderer LFootMToeA;
	ModelRenderer LFootLToeA;
	ModelRenderer LFootLToe;
	ModelRenderer RFootA;
	ModelRenderer LFootA;
	ModelRenderer LLegLower;
	ModelRenderer RLegLower;
	ModelRenderer LLegUpper;
	ModelRenderer RLegUpper;
	ModelRenderer TorsoWaist;
	ModelRenderer TorsoLower;
	ModelRenderer RLegUpperA;
	ModelRenderer LLegUpperA;
	ModelRenderer LLegLowerA;
	ModelRenderer RLegLowerA;
	ModelRenderer Tail1;
	ModelRenderer Tail2;
	ModelRenderer Tail3;
	ModelRenderer Tail4;
	ModelRenderer TorsoMiddle;
	ModelRenderer TorsoUpper;
	ModelRenderer NeckLower;
	ModelRenderer BackLowerA;
	ModelRenderer NeckA;
	ModelRenderer Head;
	ModelRenderer UpperJawLower;
	ModelRenderer UpperJawUpper;
	ModelRenderer LowerJaw;
	ModelRenderer UpperJawSnout;
	ModelRenderer LowerJawA;
	ModelRenderer RShoulder;
	ModelRenderer Lshoulder;
	ModelRenderer RArmUpper;
	ModelRenderer RArmLower;
	ModelRenderer LHandRFingerA;
	ModelRenderer LHandRFinger;
	ModelRenderer LHandMFingerA;
	ModelRenderer LHandMFinger;
	ModelRenderer LHandLFinger;
	ModelRenderer LHandLFingerA;
	ModelRenderer LArmUppder;
	ModelRenderer LArmLower;
	ModelRenderer RHandLFinger;
	ModelRenderer RHandLFingerA;
	ModelRenderer RHandMFingerA;
	ModelRenderer RHandMFinger;
	ModelRenderer RHandRFinger;
	ModelRenderer RHandRFingerA;

	public ModelWereWolf()
	{
		this.textureWidth = 64;
		this.textureHeight = 32;

		this.RFoot = new ModelRenderer(this, 0, 0);
		this.RFoot.addBox(-2F, 0F, -5F, 3, 2, 7);
		this.RFoot.setRotationPoint(-4F, 18.7F, 5.2F);
		this.RFoot.setTextureSize(64, 32);
		this.RFoot.mirror = true;
		this.setRotation(this.RFoot, 0.8726646F, 0F, 0F);
		this.LFoot = new ModelRenderer(this, 0, 0);
		this.LFoot.addBox(-1F, 0F, -5F, 3, 2, 7);
		this.LFoot.setRotationPoint(4F, 18.7F, 5.2F);
		this.LFoot.setTextureSize(64, 32);
		this.LFoot.mirror = true;
		this.setRotation(this.LFoot, 0.8726646F, 0F, 0F);
		this.RFootRToe = new ModelRenderer(this, 0, 0);
		this.RFootRToe.addBox(0F, 0F, -3F, 1, 1, 3);
		this.RFootRToe.setRotationPoint(-6F, 23F, 3.5F);
		this.RFootRToe.setTextureSize(64, 32);
		this.RFootRToe.mirror = true;
		this.setRotation(this.RFootRToe, 0F, 0.1745329F, 0F);
		this.RFootLToe = new ModelRenderer(this, 0, 0);
		this.RFootLToe.addBox(-1F, 0F, -3F, 1, 1, 3);
		this.RFootLToe.setRotationPoint(-3F, 23F, 3.5F);
		this.RFootLToe.setTextureSize(64, 32);
		this.RFootLToe.mirror = true;
		this.setRotation(this.RFootLToe, 0F, -0.1745329F, 0F);
		this.RFootRToeA = new ModelRenderer(this, 0, 0);
		this.RFootRToeA.addBox(0F, -1F, -3F, 1, 1, 3);
		this.RFootRToeA.setRotationPoint(-6F, 23F, 3.5F);
		this.RFootRToeA.setTextureSize(64, 32);
		this.RFootRToeA.mirror = true;
		this.setRotation(this.RFootRToeA, 0.1745329F, 0.1745329F, 0F);
		this.RFootLToeA = new ModelRenderer(this, 0, 0);
		this.RFootLToeA.addBox(-1F, -1F, -3F, 1, 1, 3);
		this.RFootLToeA.setRotationPoint(-3F, 23F, 3.466667F);
		this.RFootLToeA.setTextureSize(64, 32);
		this.RFootLToeA.mirror = true;
		this.setRotation(this.RFootLToeA, 0.1745329F, -0.1745329F, 0F);
		this.RFootMToe = new ModelRenderer(this, 0, 0);
		this.RFootMToe.addBox(-1F, 0F, -3F, 1, 1, 3);
		this.RFootMToe.setRotationPoint(-4F, 23F, 3.25F);
		this.RFootMToe.setTextureSize(64, 32);
		this.RFootMToe.mirror = true;
		this.setRotation(this.RFootMToe, 0F, 0F, 0F);
		this.RFootMToeA = new ModelRenderer(this, 0, 0);
		this.RFootMToeA.addBox(-1F, -1F, -3F, 1, 1, 3);
		this.RFootMToeA.setRotationPoint(-4F, 23F, 3.25F);
		this.RFootMToeA.setTextureSize(64, 32);
		this.RFootMToeA.mirror = true;
		this.setRotation(this.RFootMToeA, 0.1745329F, 0F, 0F);
		this.LFootRToe = new ModelRenderer(this, 0, 0);
		this.LFootRToe.addBox(0F, 0F, -3F, 1, 1, 3);
		this.LFootRToe.setRotationPoint(3F, 23F, 3.5F);
		this.LFootRToe.setTextureSize(64, 32);
		this.LFootRToe.mirror = true;
		this.setRotation(this.LFootRToe, 0F, 0.1745329F, 0F);
		this.LFootRToeA = new ModelRenderer(this, 0, 0);
		this.LFootRToeA.addBox(0F, -1F, -3F, 1, 1, 3);
		this.LFootRToeA.setRotationPoint(3F, 23F, 3.5F);
		this.LFootRToeA.setTextureSize(64, 32);
		this.LFootRToeA.mirror = true;
		this.setRotation(this.LFootRToeA, 0.1745329F, 0.1745329F, 0F);
		this.LFootMToe = new ModelRenderer(this, 0, 0);
		this.LFootMToe.addBox(0F, 0F, -3F, 1, 1, 3);
		this.LFootMToe.setRotationPoint(4F, 23F, 3.25F);
		this.LFootMToe.setTextureSize(64, 32);
		this.LFootMToe.mirror = true;
		this.setRotation(this.LFootMToe, 0F, 0F, 0F);
		this.LFootMToeA = new ModelRenderer(this, 0, 0);
		this.LFootMToeA.addBox(0F, -1F, -3F, 1, 1, 3);
		this.LFootMToeA.setRotationPoint(4F, 23F, 3.3F);
		this.LFootMToeA.setTextureSize(64, 32);
		this.LFootMToeA.mirror = true;
		this.setRotation(this.LFootMToeA, 0.1745329F, 0F, 0F);
		this.LFootLToeA = new ModelRenderer(this, 0, 0);
		this.LFootLToeA.addBox(-1F, -1F, -3F, 1, 1, 3);
		this.LFootLToeA.setRotationPoint(6F, 23F, 3.5F);
		this.LFootLToeA.setTextureSize(64, 32);
		this.LFootLToeA.mirror = true;
		this.setRotation(this.LFootLToeA, 0.1745329F, -0.1745329F, 0F);
		this.LFootLToe = new ModelRenderer(this, 0, 0);
		this.LFootLToe.addBox(-1F, 0F, -3F, 1, 1, 3);
		this.LFootLToe.setRotationPoint(6F, 23F, 3.5F);
		this.LFootLToe.setTextureSize(64, 32);
		this.LFootLToe.mirror = true;
		this.setRotation(this.LFootLToe, 0F, -0.1745329F, 0F);
		this.RFootA = new ModelRenderer(this, 0, 0);
		this.RFootA.addBox(-1.5F, -0.5F, -5F, 2, 2, 7);
		this.RFootA.setRotationPoint(-4F, 18.7F, 5.2F);
		this.RFootA.setTextureSize(64, 32);
		this.RFootA.mirror = true;
		this.setRotation(this.RFootA, 0.9599311F, 0F, 0F);
		this.LFootA = new ModelRenderer(this, 0, 0);
		this.LFootA.addBox(-0.5F, -0.5F, -5F, 2, 2, 7);
		this.LFootA.setRotationPoint(4F, 18.7F, 5.2F);
		this.LFootA.setTextureSize(64, 32);
		this.LFootA.mirror = true;
		this.setRotation(this.LFootA, 0.9599311F, 0F, 0F);
		this.LLegLower = new ModelRenderer(this, 0, 0);
		this.LLegLower.addBox(0F, 0F, 0F, 3, 7, 2);
		this.LLegLower.setRotationPoint(1.5F, 15F, 2.5F);
		this.LLegLower.setTextureSize(64, 32);
		this.LLegLower.mirror = true;
		this.setRotation(this.LLegLower, 1.047198F, 0.2617994F, 0F);
		this.RLegLower = new ModelRenderer(this, 0, 0);
		this.RLegLower.addBox(-3F, 0F, 0F, 3, 7, 2);
		this.RLegLower.setRotationPoint(-1.5F, 15F, 2.5F);
		this.RLegLower.setTextureSize(64, 32);
		this.RLegLower.mirror = true;
		this.setRotation(this.RLegLower, 1.047198F, -0.2617994F, 0F);
		this.LLegUpper = new ModelRenderer(this, 0, 0);
		this.LLegUpper.addBox(0F, 0F, -1F, 3, 6, 2);
		this.LLegUpper.setRotationPoint(0.5F, 9.3F, 2.5F);
		this.LLegUpper.setTextureSize(64, 32);
		this.LLegUpper.mirror = true;
		this.setRotation(this.LLegUpper, 0F, 0F, -0.1745329F);
		this.RLegUpper = new ModelRenderer(this, 0, 0);
		this.RLegUpper.addBox(-3F, 0F, -1F, 3, 6, 2);
		this.RLegUpper.setRotationPoint(-0.5F, 9.3F, 2.5F);
		this.RLegUpper.setTextureSize(64, 32);
		this.RLegUpper.mirror = true;
		this.setRotation(this.RLegUpper, 0F, 0F, 0.1745329F);
		this.TorsoWaist = new ModelRenderer(this, 0, 0);
		this.TorsoWaist.addBox(-3F, -0.3333333F, 0F, 6, 4, 4);
		this.TorsoWaist.setRotationPoint(0F, 6F, 1.5F);
		this.TorsoWaist.setTextureSize(64, 32);
		this.TorsoWaist.mirror = true;
		this.setRotation(this.TorsoWaist, -0.3490659F, 0F, 0F);
		this.TorsoLower = new ModelRenderer(this, 0, 0);
		this.TorsoLower.addBox(-3.5F, -1F, 0F, 7, 4, 4);
		this.TorsoLower.setRotationPoint(0F, 4.5F, 1.5F);
		this.TorsoLower.setTextureSize(64, 32);
		this.TorsoLower.mirror = true;
		this.setRotation(this.TorsoLower, -0.1745329F, 0F, 0F);
		this.RLegUpperA = new ModelRenderer(this, 0, 0);
		this.RLegUpperA.addBox(-2.5F, 0F, -1.5F, 2, 6, 1);
		this.RLegUpperA.setRotationPoint(-0.5F, 9.3F, 2.5F);
		this.RLegUpperA.setTextureSize(64, 32);
		this.RLegUpperA.mirror = true;
		this.setRotation(this.RLegUpperA, 0F, 0F, 0.1745329F);
		this.LLegUpperA = new ModelRenderer(this, 0, 0);
		this.LLegUpperA.addBox(0F, 0F, -1.5F, 2, 6, 1);
		this.LLegUpperA.setRotationPoint(1F, 9.3F, 2.5F);
		this.LLegUpperA.setTextureSize(64, 32);
		this.LLegUpperA.mirror = true;
		this.setRotation(this.LLegUpperA, 0F, 0F, -0.1745329F);
		this.LLegLowerA = new ModelRenderer(this, 0, 0);
		this.LLegLowerA.addBox(0.5F, -0.5F, -0.5F, 2, 7, 2);
		this.LLegLowerA.setRotationPoint(1.5F, 15F, 2.5F);
		this.LLegLowerA.setTextureSize(64, 32);
		this.LLegLowerA.mirror = true;
		this.setRotation(this.LLegLowerA, 1.047198F, 0.2617994F, 0F);
		this.RLegLowerA = new ModelRenderer(this, 0, 0);
		this.RLegLowerA.addBox(-2.5F, -0.5F, -0.5F, 2, 7, 2);
		this.RLegLowerA.setRotationPoint(-1.5F, 15F, 2.5F);
		this.RLegLowerA.setTextureSize(64, 32);
		this.RLegLowerA.mirror = true;
		this.setRotation(this.RLegLowerA, 1.047198F, -0.2617994F, 0F);
		this.Tail1 = new ModelRenderer(this, 0, 0);
		this.Tail1.addBox(-1.5F, 0F, 0F, 3, 2, 3);
		this.Tail1.setRotationPoint(0F, 9.5F, 3.5F);
		this.Tail1.setTextureSize(64, 32);
		this.Tail1.mirror = true;
		this.setRotation(this.Tail1, 1.134464F, 0F, 0F);
		this.Tail1.mirror = false;
		this.Tail2 = new ModelRenderer(this, 0, 0);
		this.Tail2.addBox(-1.5F, 0F, -1.5F, 3, 3, 3);
		this.Tail2.setRotationPoint(0F, 9F, 5.5F);
		this.Tail2.setTextureSize(64, 32);
		this.Tail2.mirror = true;
		this.setRotation(this.Tail2, 1.22173F, 0F, 0F);
		this.Tail3 = new ModelRenderer(this, 0, 0);
		this.Tail3.addBox(-1.5F, 0F, -1F, 3, 5, 2);
		this.Tail3.setRotationPoint(0F, 10F, 8F);
		this.Tail3.setTextureSize(64, 32);
		this.Tail3.mirror = true;
		this.setRotation(this.Tail3, 1.396263F, 0F, 0F);
		this.Tail4 = new ModelRenderer(this, 0, 0);
		this.Tail4.addBox(-1F, 0F, -0.8F, 2, 5, 2);
		this.Tail4.setRotationPoint(0F, 11F, 12F);
		this.Tail4.setTextureSize(64, 32);
		this.Tail4.mirror = true;
		this.setRotation(this.Tail4, 1.745329F, 0F, 0F);
		this.TorsoMiddle = new ModelRenderer(this, 0, 0);
		this.TorsoMiddle.addBox(-4F, 0F, 0F, 8, 4, 5);
		this.TorsoMiddle.setRotationPoint(0F, 0.5F, 0.9F);
		this.TorsoMiddle.setTextureSize(64, 32);
		this.TorsoMiddle.mirror = true;
		this.setRotation(this.TorsoMiddle, 0.0872665F, 0F, 0F);
		this.TorsoUpper = new ModelRenderer(this, 0, 0);
		this.TorsoUpper.addBox(-4.5F, 0F, 0F, 9, 4, 5);
		this.TorsoUpper.setRotationPoint(0F, -2F, 0F);
		this.TorsoUpper.setTextureSize(64, 32);
		this.TorsoUpper.mirror = true;
		this.setRotation(this.TorsoUpper, 0.2617994F, 0F, 0F);
		this.NeckLower = new ModelRenderer(this, 0, 0);
		this.NeckLower.addBox(-3.5F, 0.5F, -1F, 7, 2, 5);
		this.NeckLower.setRotationPoint(0F, -3F, 0.2F);
		this.NeckLower.setTextureSize(64, 32);
		this.NeckLower.mirror = true;
		this.setRotation(this.NeckLower, 0.5235988F, 0F, 0F);
		this.BackLowerA = new ModelRenderer(this, 0, 0);
		this.BackLowerA.addBox(-3F, -1F, -1F, 6, 5, 2);
		this.BackLowerA.setRotationPoint(0F, 4F, 5F);
		this.BackLowerA.setTextureSize(64, 32);
		this.BackLowerA.mirror = true;
		this.setRotation(this.BackLowerA, -0.1570796F, 0F, 0F);
		this.NeckA = new ModelRenderer(this, 0, 0);
		this.NeckA.addBox(-2F, -1F, -2.5F, 4, 2, 5);
		this.NeckA.setRotationPoint(0F, -3.5F, 1F);
		this.NeckA.setTextureSize(64, 32);
		this.NeckA.mirror = true;
		this.setRotation(this.NeckA, 0.6981317F, 0F, 0F);
		this.Head = new ModelRenderer(this, 29, 0);
		this.Head.addBox(-2.5F, -5F, -2F, 5, 5, 5);
		this.Head.setRotationPoint(0F, -3F, 0F);
		this.Head.setTextureSize(64, 32);
		this.Head.mirror = true;
		this.setRotation(this.Head, 0.3490659F, 0F, 0F);
		this.UpperJawLower = new ModelRenderer(this, 13, 11);
		this.UpperJawLower.addBox(-1.5F, -3F, -4.45F, 3, 1, 3);
		this.UpperJawLower.setRotationPoint(0F, -2F, 0F);
		this.UpperJawLower.setTextureSize(64, 32);
		this.UpperJawLower.mirror = true;
		this.setRotation(this.UpperJawLower, 0.3490659F, 0F, 0F);
		this.UpperJawUpper = new ModelRenderer(this, 0, 0);
		this.UpperJawUpper.addBox(-1.5F, -4.2F, -3.9F, 3, 1, 3);
		this.UpperJawUpper.setRotationPoint(0F, -2F, 0F);
		this.UpperJawUpper.setTextureSize(64, 32);
		this.UpperJawUpper.mirror = true;
		this.setRotation(this.UpperJawUpper, 0.5235988F, 0F, 0F);
		this.LowerJaw = new ModelRenderer(this, 0, 11);
		this.LowerJaw.addBox(-1.5F, 0F, -2.8F, 3, 1, 3);
		this.LowerJaw.setRotationPoint(0F, -3F, -2F);
		this.LowerJaw.setTextureSize(64, 32);
		this.LowerJaw.mirror = true;
		this.setRotation(this.LowerJaw, 0.6981317F, 0F, 0F);
		this.UpperJawSnout = new ModelRenderer(this, 0, 0);
		this.UpperJawSnout.addBox(-0.5F, 0F, -3F, 1, 1, 4);
		this.UpperJawSnout.setRotationPoint(0F, -6F, -3.5F);
		this.UpperJawSnout.setTextureSize(64, 32);
		this.UpperJawSnout.mirror = true;
		this.setRotation(this.UpperJawSnout, 0.6981317F, 0F, 0F);
		this.LowerJawA = new ModelRenderer(this, 0, 0);
		this.LowerJawA.addBox(-1F, 1F, -2.5F, 2, 1, 4);
		this.LowerJawA.setRotationPoint(0F, -3F, -2F);
		this.LowerJawA.setTextureSize(64, 32);
		this.LowerJawA.mirror = true;
		this.setRotation(this.LowerJawA, 0.4363323F, 0F, 0F);
		this.RShoulder = new ModelRenderer(this, 0, 0);
		this.RShoulder.addBox(-2F, -1F, -2F, 3, 3, 3);
		this.RShoulder.setRotationPoint(-5F, -2F, 3F);
		this.RShoulder.setTextureSize(64, 32);
		this.RShoulder.mirror = true;
		this.setRotation(this.RShoulder, 0F, 0F, -0.2617994F);
		this.Lshoulder = new ModelRenderer(this, 0, 0);
		this.Lshoulder.addBox(-1F, -1F, -2F, 3, 3, 3);
		this.Lshoulder.setRotationPoint(5F, -2F, 3F);
		this.Lshoulder.setTextureSize(64, 32);
		this.Lshoulder.mirror = true;
		this.setRotation(this.Lshoulder, 0F, 0F, 0.2617994F);
		this.RArmUpper = new ModelRenderer(this, 0, 0);
		this.RArmUpper.addBox(-0.5F, -1F, -7F, 2, 2, 8);
		this.RArmUpper.setRotationPoint(-7F, -1F, 2.5F);
		this.RArmUpper.setTextureSize(64, 32);
		this.RArmUpper.mirror = true;
		this.setRotation(this.RArmUpper, 1.919862F, 0F, 0.5235988F);
		this.RArmLower = new ModelRenderer(this, 0, 0);
		this.RArmLower.addBox(-0.8F, -1F, -0.7F, 2, 2, 7);
		this.RArmLower.setRotationPoint(-10F, 5F, 5F);
		this.RArmLower.setTextureSize(64, 32);
		this.RArmLower.mirror = true;
		this.setRotation(this.RArmLower, -2.617994F, 0F, 0F);
		this.LHandRFingerA = new ModelRenderer(this, 0, 0);
		this.LHandRFingerA.addBox(0F, 0F, 0F, 1, 1, 3);
		this.LHandRFingerA.setRotationPoint(8.5F, 7.5F, 1F);
		this.LHandRFingerA.setTextureSize(64, 32);
		this.LHandRFingerA.mirror = true;
		this.setRotation(this.LHandRFingerA, -2.268928F, 0.2617994F, 0F);
		this.LHandRFinger = new ModelRenderer(this, 0, 0);
		this.LHandRFinger.addBox(0F, -1F, 0F, 1, 1, 3);
		this.LHandRFinger.setRotationPoint(8.5F, 7.5F, 1F);
		this.LHandRFinger.setTextureSize(64, 32);
		this.LHandRFinger.mirror = true;
		this.setRotation(this.LHandRFinger, -2.443461F, 0.2617994F, 0F);
		this.LHandMFingerA = new ModelRenderer(this, 0, 0);
		this.LHandMFingerA.addBox(0F, 0F, 0F, 1, 1, 3);
		this.LHandMFingerA.setRotationPoint(9.3F, 7.8F, 0F);
		this.LHandMFingerA.setTextureSize(64, 32);
		this.LHandMFingerA.mirror = true;
		this.setRotation(this.LHandMFingerA, -2.268928F, 0F, 0F);
		this.LHandMFinger = new ModelRenderer(this, 0, 0);
		this.LHandMFinger.addBox(0F, -1F, 0F, 1, 1, 3);
		this.LHandMFinger.setRotationPoint(9.3F, 7.8F, 0F);
		this.LHandMFinger.setTextureSize(64, 32);
		this.LHandMFinger.mirror = true;
		this.setRotation(this.LHandMFinger, -2.443461F, 0F, 0F);
		this.LHandLFinger = new ModelRenderer(this, 0, 0);
		this.LHandLFinger.addBox(0F, -1F, 0F, 1, 1, 3);
		this.LHandLFinger.setRotationPoint(10F, 7.5F, 1F);
		this.LHandLFinger.setTextureSize(64, 32);
		this.LHandLFinger.mirror = true;
		this.setRotation(this.LHandLFinger, -2.443461F, -0.2617994F, 0F);
		this.LHandLFingerA = new ModelRenderer(this, 0, 0);
		this.LHandLFingerA.addBox(0F, 0F, 0F, 1, 1, 3);
		this.LHandLFingerA.setRotationPoint(10F, 7.5F, 1F);
		this.LHandLFingerA.setTextureSize(64, 32);
		this.LHandLFingerA.mirror = true;
		this.setRotation(this.LHandLFingerA, -2.268928F, -0.2617994F, 0F);
		this.LArmUppder = new ModelRenderer(this, 0, 0);
		this.LArmUppder.addBox(-1.5F, -1F, -1F, 2, 2, 8);
		this.LArmUppder.setRotationPoint(7F, -1F, 2.5F);
		this.LArmUppder.setTextureSize(64, 32);
		this.LArmUppder.mirror = true;
		this.setRotation(this.LArmUppder, -1.22173F, 0F, -0.5235988F);
		this.LArmLower = new ModelRenderer(this, 0, 0);
		this.LArmLower.addBox(-0.8F, -1F, -0.7F, 2, 2, 7);
		this.LArmLower.setRotationPoint(9.5F, 5F, 5F);
		this.LArmLower.setTextureSize(64, 32);
		this.LArmLower.mirror = true;
		this.setRotation(this.LArmLower, -2.617994F, 0F, 0F);
		this.RHandLFinger = new ModelRenderer(this, 0, 0);
		this.RHandLFinger.addBox(0F, -1F, 0F, 1, 1, 3);
		this.RHandLFinger.setRotationPoint(-9.5F, 7.5F, 1F);
		this.RHandLFinger.setTextureSize(64, 32);
		this.RHandLFinger.mirror = true;
		this.setRotation(this.RHandLFinger, -2.443461F, -0.2617994F, 0F);
		this.RHandLFingerA = new ModelRenderer(this, 0, 0);
		this.RHandLFingerA.addBox(0F, 0F, 0F, 1, 1, 3);
		this.RHandLFingerA.setRotationPoint(-9.5F, 7.5F, 1F);
		this.RHandLFingerA.setTextureSize(64, 32);
		this.RHandLFingerA.mirror = true;
		this.setRotation(this.RHandLFingerA, -2.268928F, -0.2617994F, 0F);
		this.RHandMFingerA = new ModelRenderer(this, 0, 0);
		this.RHandMFingerA.addBox(0F, 0F, 0F, 1, 1, 3);
		this.RHandMFingerA.setRotationPoint(-10.2F, 7.8F, 0F);
		this.RHandMFingerA.setTextureSize(64, 32);
		this.RHandMFingerA.mirror = true;
		this.setRotation(this.RHandMFingerA, -2.268928F, 0F, 0F);
		this.RHandMFinger = new ModelRenderer(this, 0, 0);
		this.RHandMFinger.addBox(0F, -1F, 0F, 1, 1, 3);
		this.RHandMFinger.setRotationPoint(-10.2F, 7.8F, 0F);
		this.RHandMFinger.setTextureSize(64, 32);
		this.RHandMFinger.mirror = true;
		this.setRotation(this.RHandMFinger, -2.443461F, 0F, 0F);
		this.RHandRFinger = new ModelRenderer(this, 0, 0);
		this.RHandRFinger.addBox(0F, -1F, 0F, 1, 1, 3);
		this.RHandRFinger.setRotationPoint(-11F, 7.5F, 1F);
		this.RHandRFinger.setTextureSize(64, 32);
		this.RHandRFinger.mirror = true;
		this.setRotation(this.RHandRFinger, -2.443461F, 0.2617994F, 0F);
		this.RHandRFingerA = new ModelRenderer(this, 0, 0);
		this.RHandRFingerA.addBox(0F, 0F, 0F, 1, 1, 3);
		this.RHandRFingerA.setRotationPoint(-11F, 7.5F, 1F);
		this.RHandRFingerA.setTextureSize(64, 32);
		this.RHandRFingerA.mirror = true;
		this.setRotation(this.RHandRFingerA, -2.268928F, 0.2617994F, 0F);
	}

	@Override
	public void render(final Entity entity, final float f, final float f1, final float f2, final float f3, final float f4, final float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		this.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		this.RFoot.render(f5);
		this.LFoot.render(f5);
		this.RFootRToe.render(f5);
		this.RFootLToe.render(f5);
		this.RFootRToeA.render(f5);
		this.RFootLToeA.render(f5);
		this.RFootMToe.render(f5);
		this.RFootMToeA.render(f5);
		this.LFootRToe.render(f5);
		this.LFootRToeA.render(f5);
		this.LFootMToe.render(f5);
		this.LFootMToeA.render(f5);
		this.LFootLToeA.render(f5);
		this.LFootLToe.render(f5);
		this.RFootA.render(f5);
		this.LFootA.render(f5);
		this.LLegLower.render(f5);
		this.RLegLower.render(f5);
		this.LLegUpper.render(f5);
		this.RLegUpper.render(f5);
		this.TorsoWaist.render(f5);
		this.TorsoLower.render(f5);
		this.RLegUpperA.render(f5);
		this.LLegUpperA.render(f5);
		this.LLegLowerA.render(f5);
		this.RLegLowerA.render(f5);
		this.Tail1.render(f5);
		this.Tail2.render(f5);
		this.Tail3.render(f5);
		this.Tail4.render(f5);
		this.TorsoMiddle.render(f5);
		this.TorsoUpper.render(f5);
		this.NeckLower.render(f5);
		this.BackLowerA.render(f5);
		this.NeckA.render(f5);
		this.Head.render(f5);
		this.UpperJawLower.render(f5);
		this.UpperJawUpper.render(f5);
		this.LowerJaw.render(f5);
		this.UpperJawSnout.render(f5);
		this.LowerJawA.render(f5);
		this.RShoulder.render(f5);
		this.Lshoulder.render(f5);
		this.RArmUpper.render(f5);
		this.RArmLower.render(f5);
		this.LHandRFingerA.render(f5);
		this.LHandRFinger.render(f5);
		this.LHandMFingerA.render(f5);
		this.LHandMFinger.render(f5);
		this.LHandLFinger.render(f5);
		this.LHandLFingerA.render(f5);
		this.LArmUppder.render(f5);
		this.LArmLower.render(f5);
		this.RHandLFinger.render(f5);
		this.RHandLFingerA.render(f5);
		this.RHandMFingerA.render(f5);
		this.RHandMFinger.render(f5);
		this.RHandRFinger.render(f5);
		this.RHandRFingerA.render(f5);
	}

	private void setRotation(final ModelRenderer model, final float x, final float y, final float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	@Override
	public void setRotationAngles(final float f, final float f1, final float f2, final float f3, final float f4, final float f5, final Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
