/*
 * Author: David Slovikosky
 * Mod: Afraid of the Dark
 * Ideas and Textures: Michael Albertson
 */
package com.DavidM1A2.AfraidOfTheDark.entities.WereWolf;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

// Werewolf model by Michael Albertson
public class ModelWereWolf extends ModelBase
{
	// fields
	ModelRenderer RFoot;
	ModelRenderer LFoot;
	ModelRenderer RFootRToe;
	ModelRenderer RFootLToe;
	ModelRenderer RFootRToeA;
	ModelRenderer RFootLToeA;
	ModelRenderer RFootMToe;
	ModelRenderer RFootMToeA;
	ModelRenderer LFootRToe;
	ModelRenderer LFootRToeA;
	ModelRenderer LFootMToe;
	ModelRenderer LFootMToeA;
	ModelRenderer LFootLToeA;
	ModelRenderer LFootLToe;
	ModelRenderer RFootA;
	ModelRenderer LFootA;
	ModelRenderer LLegLower;
	ModelRenderer RLegLower;
	ModelRenderer LLegUpper;
	ModelRenderer RLegUpper;
	ModelRenderer TorsoWaist;
	ModelRenderer TorsoLower;
	ModelRenderer RLegUpperA;
	ModelRenderer LLegUpperA;
	ModelRenderer LLegLowerA;
	ModelRenderer RLegLowerA;
	ModelRenderer Tail1;
	ModelRenderer Tail2;
	ModelRenderer Tail3;
	ModelRenderer Tail4;
	ModelRenderer TorsoMiddle;
	ModelRenderer TorsoUpper;
	ModelRenderer NeckLower;
	ModelRenderer BackLowerA;
	ModelRenderer NeckA;
	ModelRenderer Head;
	ModelRenderer UpperJawLower;
	ModelRenderer UpperJawUpper;
	ModelRenderer LowerJaw;
	ModelRenderer UpperJawSnout;
	ModelRenderer LowerJawA;
	ModelRenderer RShoulder;
	ModelRenderer Lshoulder;
	ModelRenderer RArmUpper;
	ModelRenderer RArmLower;
	ModelRenderer LHandRFingerA;
	ModelRenderer LHandRFinger;
	ModelRenderer LHandMFingerA;
	ModelRenderer LHandMFinger;
	ModelRenderer LHandLFinger;
	ModelRenderer LHandLFingerA;
	ModelRenderer LArmUppder;
	ModelRenderer LArmLower;
	ModelRenderer RHandLFinger;
	ModelRenderer RHandLFingerA;
	ModelRenderer RHandMFingerA;
	ModelRenderer RHandMFinger;
	ModelRenderer RHandRFinger;
	ModelRenderer RHandRFingerA;

	public ModelWereWolf()
	{
		textureWidth = 64;
		textureHeight = 32;

		RFoot = new ModelRenderer(this, 0, 0);
		RFoot.addBox(-2F, 0F, -5F, 3, 2, 7);
		RFoot.setRotationPoint(-4F, 18.7F, 5.2F);
		RFoot.setTextureSize(64, 32);
		RFoot.mirror = true;
		setRotation(RFoot, 0.8726646F, 0F, 0F);
		LFoot = new ModelRenderer(this, 0, 0);
		LFoot.addBox(-1F, 0F, -5F, 3, 2, 7);
		LFoot.setRotationPoint(4F, 18.7F, 5.2F);
		LFoot.setTextureSize(64, 32);
		LFoot.mirror = true;
		setRotation(LFoot, 0.8726646F, 0F, 0F);
		RFootRToe = new ModelRenderer(this, 0, 0);
		RFootRToe.addBox(0F, 0F, -3F, 1, 1, 3);
		RFootRToe.setRotationPoint(-6F, 23F, 3.5F);
		RFootRToe.setTextureSize(64, 32);
		RFootRToe.mirror = true;
		setRotation(RFootRToe, 0F, 0.1745329F, 0F);
		RFootLToe = new ModelRenderer(this, 0, 0);
		RFootLToe.addBox(-1F, 0F, -3F, 1, 1, 3);
		RFootLToe.setRotationPoint(-3F, 23F, 3.5F);
		RFootLToe.setTextureSize(64, 32);
		RFootLToe.mirror = true;
		setRotation(RFootLToe, 0F, -0.1745329F, 0F);
		RFootRToeA = new ModelRenderer(this, 0, 0);
		RFootRToeA.addBox(0F, -1F, -3F, 1, 1, 3);
		RFootRToeA.setRotationPoint(-6F, 23F, 3.5F);
		RFootRToeA.setTextureSize(64, 32);
		RFootRToeA.mirror = true;
		setRotation(RFootRToeA, 0.1745329F, 0.1745329F, 0F);
		RFootLToeA = new ModelRenderer(this, 0, 0);
		RFootLToeA.addBox(-1F, -1F, -3F, 1, 1, 3);
		RFootLToeA.setRotationPoint(-3F, 23F, 3.466667F);
		RFootLToeA.setTextureSize(64, 32);
		RFootLToeA.mirror = true;
		setRotation(RFootLToeA, 0.1745329F, -0.1745329F, 0F);
		RFootMToe = new ModelRenderer(this, 0, 0);
		RFootMToe.addBox(-1F, 0F, -3F, 1, 1, 3);
		RFootMToe.setRotationPoint(-4F, 23F, 3.25F);
		RFootMToe.setTextureSize(64, 32);
		RFootMToe.mirror = true;
		setRotation(RFootMToe, 0F, 0F, 0F);
		RFootMToeA = new ModelRenderer(this, 0, 0);
		RFootMToeA.addBox(-1F, -1F, -3F, 1, 1, 3);
		RFootMToeA.setRotationPoint(-4F, 23F, 3.25F);
		RFootMToeA.setTextureSize(64, 32);
		RFootMToeA.mirror = true;
		setRotation(RFootMToeA, 0.1745329F, 0F, 0F);
		LFootRToe = new ModelRenderer(this, 0, 0);
		LFootRToe.addBox(0F, 0F, -3F, 1, 1, 3);
		LFootRToe.setRotationPoint(3F, 23F, 3.5F);
		LFootRToe.setTextureSize(64, 32);
		LFootRToe.mirror = true;
		setRotation(LFootRToe, 0F, 0.1745329F, 0F);
		LFootRToeA = new ModelRenderer(this, 0, 0);
		LFootRToeA.addBox(0F, -1F, -3F, 1, 1, 3);
		LFootRToeA.setRotationPoint(3F, 23F, 3.5F);
		LFootRToeA.setTextureSize(64, 32);
		LFootRToeA.mirror = true;
		setRotation(LFootRToeA, 0.1745329F, 0.1745329F, 0F);
		LFootMToe = new ModelRenderer(this, 0, 0);
		LFootMToe.addBox(0F, 0F, -3F, 1, 1, 3);
		LFootMToe.setRotationPoint(4F, 23F, 3.25F);
		LFootMToe.setTextureSize(64, 32);
		LFootMToe.mirror = true;
		setRotation(LFootMToe, 0F, 0F, 0F);
		LFootMToeA = new ModelRenderer(this, 0, 0);
		LFootMToeA.addBox(0F, -1F, -3F, 1, 1, 3);
		LFootMToeA.setRotationPoint(4F, 23F, 3.3F);
		LFootMToeA.setTextureSize(64, 32);
		LFootMToeA.mirror = true;
		setRotation(LFootMToeA, 0.1745329F, 0F, 0F);
		LFootLToeA = new ModelRenderer(this, 0, 0);
		LFootLToeA.addBox(-1F, -1F, -3F, 1, 1, 3);
		LFootLToeA.setRotationPoint(6F, 23F, 3.5F);
		LFootLToeA.setTextureSize(64, 32);
		LFootLToeA.mirror = true;
		setRotation(LFootLToeA, 0.1745329F, -0.1745329F, 0F);
		LFootLToe = new ModelRenderer(this, 0, 0);
		LFootLToe.addBox(-1F, 0F, -3F, 1, 1, 3);
		LFootLToe.setRotationPoint(6F, 23F, 3.5F);
		LFootLToe.setTextureSize(64, 32);
		LFootLToe.mirror = true;
		setRotation(LFootLToe, 0F, -0.1745329F, 0F);
		RFootA = new ModelRenderer(this, 0, 0);
		RFootA.addBox(-1.5F, -0.5F, -5F, 2, 2, 7);
		RFootA.setRotationPoint(-4F, 18.7F, 5.2F);
		RFootA.setTextureSize(64, 32);
		RFootA.mirror = true;
		setRotation(RFootA, 0.9599311F, 0F, 0F);
		LFootA = new ModelRenderer(this, 0, 0);
		LFootA.addBox(-0.5F, -0.5F, -5F, 2, 2, 7);
		LFootA.setRotationPoint(4F, 18.7F, 5.2F);
		LFootA.setTextureSize(64, 32);
		LFootA.mirror = true;
		setRotation(LFootA, 0.9599311F, 0F, 0F);
		LLegLower = new ModelRenderer(this, 0, 0);
		LLegLower.addBox(0F, 0F, 0F, 3, 7, 2);
		LLegLower.setRotationPoint(1.5F, 15F, 2.5F);
		LLegLower.setTextureSize(64, 32);
		LLegLower.mirror = true;
		setRotation(LLegLower, 1.047198F, 0.2617994F, 0F);
		RLegLower = new ModelRenderer(this, 0, 0);
		RLegLower.addBox(-3F, 0F, 0F, 3, 7, 2);
		RLegLower.setRotationPoint(-1.5F, 15F, 2.5F);
		RLegLower.setTextureSize(64, 32);
		RLegLower.mirror = true;
		setRotation(RLegLower, 1.047198F, -0.2617994F, 0F);
		LLegUpper = new ModelRenderer(this, 0, 0);
		LLegUpper.addBox(0F, 0F, -1F, 3, 6, 2);
		LLegUpper.setRotationPoint(0.5F, 9.3F, 2.5F);
		LLegUpper.setTextureSize(64, 32);
		LLegUpper.mirror = true;
		setRotation(LLegUpper, 0F, 0F, -0.1745329F);
		RLegUpper = new ModelRenderer(this, 0, 0);
		RLegUpper.addBox(-3F, 0F, -1F, 3, 6, 2);
		RLegUpper.setRotationPoint(-0.5F, 9.3F, 2.5F);
		RLegUpper.setTextureSize(64, 32);
		RLegUpper.mirror = true;
		setRotation(RLegUpper, 0F, 0F, 0.1745329F);
		TorsoWaist = new ModelRenderer(this, 0, 0);
		TorsoWaist.addBox(-3F, -0.3333333F, 0F, 6, 4, 4);
		TorsoWaist.setRotationPoint(0F, 6F, 1.5F);
		TorsoWaist.setTextureSize(64, 32);
		TorsoWaist.mirror = true;
		setRotation(TorsoWaist, -0.3490659F, 0F, 0F);
		TorsoLower = new ModelRenderer(this, 0, 0);
		TorsoLower.addBox(-3.5F, -1F, 0F, 7, 4, 4);
		TorsoLower.setRotationPoint(0F, 4.5F, 1.5F);
		TorsoLower.setTextureSize(64, 32);
		TorsoLower.mirror = true;
		setRotation(TorsoLower, -0.1745329F, 0F, 0F);
		RLegUpperA = new ModelRenderer(this, 0, 0);
		RLegUpperA.addBox(-2.5F, 0F, -1.5F, 2, 6, 1);
		RLegUpperA.setRotationPoint(-0.5F, 9.3F, 2.5F);
		RLegUpperA.setTextureSize(64, 32);
		RLegUpperA.mirror = true;
		setRotation(RLegUpperA, 0F, 0F, 0.1745329F);
		LLegUpperA = new ModelRenderer(this, 0, 0);
		LLegUpperA.addBox(0F, 0F, -1.5F, 2, 6, 1);
		LLegUpperA.setRotationPoint(1F, 9.3F, 2.5F);
		LLegUpperA.setTextureSize(64, 32);
		LLegUpperA.mirror = true;
		setRotation(LLegUpperA, 0F, 0F, -0.1745329F);
		LLegLowerA = new ModelRenderer(this, 0, 0);
		LLegLowerA.addBox(0.5F, -0.5F, -0.5F, 2, 7, 2);
		LLegLowerA.setRotationPoint(1.5F, 15F, 2.5F);
		LLegLowerA.setTextureSize(64, 32);
		LLegLowerA.mirror = true;
		setRotation(LLegLowerA, 1.047198F, 0.2617994F, 0F);
		RLegLowerA = new ModelRenderer(this, 0, 0);
		RLegLowerA.addBox(-2.5F, -0.5F, -0.5F, 2, 7, 2);
		RLegLowerA.setRotationPoint(-1.5F, 15F, 2.5F);
		RLegLowerA.setTextureSize(64, 32);
		RLegLowerA.mirror = true;
		setRotation(RLegLowerA, 1.047198F, -0.2617994F, 0F);
		Tail1 = new ModelRenderer(this, 0, 0);
		Tail1.addBox(-1.5F, 0F, 0F, 3, 2, 3);
		Tail1.setRotationPoint(0F, 9.5F, 3.5F);
		Tail1.setTextureSize(64, 32);
		Tail1.mirror = true;
		setRotation(Tail1, 1.134464F, 0F, 0F);
		Tail1.mirror = false;
		Tail2 = new ModelRenderer(this, 0, 0);
		Tail2.addBox(-1.5F, 0F, -1.5F, 3, 3, 3);
		Tail2.setRotationPoint(0F, 9F, 5.5F);
		Tail2.setTextureSize(64, 32);
		Tail2.mirror = true;
		setRotation(Tail2, 1.22173F, 0F, 0F);
		Tail3 = new ModelRenderer(this, 0, 0);
		Tail3.addBox(-1.5F, 0F, -1F, 3, 5, 2);
		Tail3.setRotationPoint(0F, 10F, 8F);
		Tail3.setTextureSize(64, 32);
		Tail3.mirror = true;
		setRotation(Tail3, 1.396263F, 0F, 0F);
		Tail4 = new ModelRenderer(this, 0, 0);
		Tail4.addBox(-1F, 0F, -0.8F, 2, 5, 2);
		Tail4.setRotationPoint(0F, 11F, 12F);
		Tail4.setTextureSize(64, 32);
		Tail4.mirror = true;
		setRotation(Tail4, 1.745329F, 0F, 0F);
		TorsoMiddle = new ModelRenderer(this, 0, 0);
		TorsoMiddle.addBox(-4F, 0F, 0F, 8, 4, 5);
		TorsoMiddle.setRotationPoint(0F, 0.5F, 0.9F);
		TorsoMiddle.setTextureSize(64, 32);
		TorsoMiddle.mirror = true;
		setRotation(TorsoMiddle, 0.0872665F, 0F, 0F);
		TorsoUpper = new ModelRenderer(this, 0, 0);
		TorsoUpper.addBox(-4.5F, 0F, 0F, 9, 4, 5);
		TorsoUpper.setRotationPoint(0F, -2F, 0F);
		TorsoUpper.setTextureSize(64, 32);
		TorsoUpper.mirror = true;
		setRotation(TorsoUpper, 0.2617994F, 0F, 0F);
		NeckLower = new ModelRenderer(this, 0, 0);
		NeckLower.addBox(-3.5F, 0.5F, -1F, 7, 2, 5);
		NeckLower.setRotationPoint(0F, -3F, 0.2F);
		NeckLower.setTextureSize(64, 32);
		NeckLower.mirror = true;
		setRotation(NeckLower, 0.5235988F, 0F, 0F);
		BackLowerA = new ModelRenderer(this, 0, 0);
		BackLowerA.addBox(-3F, -1F, -1F, 6, 5, 2);
		BackLowerA.setRotationPoint(0F, 4F, 5F);
		BackLowerA.setTextureSize(64, 32);
		BackLowerA.mirror = true;
		setRotation(BackLowerA, -0.1570796F, 0F, 0F);
		NeckA = new ModelRenderer(this, 0, 0);
		NeckA.addBox(-2F, -1F, -2.5F, 4, 2, 5);
		NeckA.setRotationPoint(0F, -3.5F, 1F);
		NeckA.setTextureSize(64, 32);
		NeckA.mirror = true;
		setRotation(NeckA, 0.6981317F, 0F, 0F);
		Head = new ModelRenderer(this, 29, 0);
		Head.addBox(-2.5F, -5F, -2F, 5, 5, 5);
		Head.setRotationPoint(0F, -3F, 0F);
		Head.setTextureSize(64, 32);
		Head.mirror = true;
		setRotation(Head, 0.3490659F, 0F, 0F);
		UpperJawLower = new ModelRenderer(this, 13, 11);
		UpperJawLower.addBox(-1.5F, -3F, -4.45F, 3, 1, 3);
		UpperJawLower.setRotationPoint(0F, -2F, 0F);
		UpperJawLower.setTextureSize(64, 32);
		UpperJawLower.mirror = true;
		setRotation(UpperJawLower, 0.3490659F, 0F, 0F);
		UpperJawUpper = new ModelRenderer(this, 0, 0);
		UpperJawUpper.addBox(-1.5F, -4.2F, -3.9F, 3, 1, 3);
		UpperJawUpper.setRotationPoint(0F, -2F, 0F);
		UpperJawUpper.setTextureSize(64, 32);
		UpperJawUpper.mirror = true;
		setRotation(UpperJawUpper, 0.5235988F, 0F, 0F);
		LowerJaw = new ModelRenderer(this, 0, 11);
		LowerJaw.addBox(-1.5F, 0F, -2.8F, 3, 1, 3);
		LowerJaw.setRotationPoint(0F, -3F, -2F);
		LowerJaw.setTextureSize(64, 32);
		LowerJaw.mirror = true;
		setRotation(LowerJaw, 0.6981317F, 0F, 0F);
		UpperJawSnout = new ModelRenderer(this, 0, 0);
		UpperJawSnout.addBox(-0.5F, 0F, -3F, 1, 1, 4);
		UpperJawSnout.setRotationPoint(0F, -6F, -3.5F);
		UpperJawSnout.setTextureSize(64, 32);
		UpperJawSnout.mirror = true;
		setRotation(UpperJawSnout, 0.6981317F, 0F, 0F);
		LowerJawA = new ModelRenderer(this, 0, 0);
		LowerJawA.addBox(-1F, 1F, -2.5F, 2, 1, 4);
		LowerJawA.setRotationPoint(0F, -3F, -2F);
		LowerJawA.setTextureSize(64, 32);
		LowerJawA.mirror = true;
		setRotation(LowerJawA, 0.4363323F, 0F, 0F);
		RShoulder = new ModelRenderer(this, 0, 0);
		RShoulder.addBox(-2F, -1F, -2F, 3, 3, 3);
		RShoulder.setRotationPoint(-5F, -2F, 3F);
		RShoulder.setTextureSize(64, 32);
		RShoulder.mirror = true;
		setRotation(RShoulder, 0F, 0F, -0.2617994F);
		Lshoulder = new ModelRenderer(this, 0, 0);
		Lshoulder.addBox(-1F, -1F, -2F, 3, 3, 3);
		Lshoulder.setRotationPoint(5F, -2F, 3F);
		Lshoulder.setTextureSize(64, 32);
		Lshoulder.mirror = true;
		setRotation(Lshoulder, 0F, 0F, 0.2617994F);
		RArmUpper = new ModelRenderer(this, 0, 0);
		RArmUpper.addBox(-0.5F, -1F, -7F, 2, 2, 8);
		RArmUpper.setRotationPoint(-7F, -1F, 2.5F);
		RArmUpper.setTextureSize(64, 32);
		RArmUpper.mirror = true;
		setRotation(RArmUpper, 1.919862F, 0F, 0.5235988F);
		RArmLower = new ModelRenderer(this, 0, 0);
		RArmLower.addBox(-0.8F, -1F, -0.7F, 2, 2, 7);
		RArmLower.setRotationPoint(-10F, 5F, 5F);
		RArmLower.setTextureSize(64, 32);
		RArmLower.mirror = true;
		setRotation(RArmLower, -2.617994F, 0F, 0F);
		LHandRFingerA = new ModelRenderer(this, 0, 0);
		LHandRFingerA.addBox(0F, 0F, 0F, 1, 1, 3);
		LHandRFingerA.setRotationPoint(8.5F, 7.5F, 1F);
		LHandRFingerA.setTextureSize(64, 32);
		LHandRFingerA.mirror = true;
		setRotation(LHandRFingerA, -2.268928F, 0.2617994F, 0F);
		LHandRFinger = new ModelRenderer(this, 0, 0);
		LHandRFinger.addBox(0F, -1F, 0F, 1, 1, 3);
		LHandRFinger.setRotationPoint(8.5F, 7.5F, 1F);
		LHandRFinger.setTextureSize(64, 32);
		LHandRFinger.mirror = true;
		setRotation(LHandRFinger, -2.443461F, 0.2617994F, 0F);
		LHandMFingerA = new ModelRenderer(this, 0, 0);
		LHandMFingerA.addBox(0F, 0F, 0F, 1, 1, 3);
		LHandMFingerA.setRotationPoint(9.3F, 7.8F, 0F);
		LHandMFingerA.setTextureSize(64, 32);
		LHandMFingerA.mirror = true;
		setRotation(LHandMFingerA, -2.268928F, 0F, 0F);
		LHandMFinger = new ModelRenderer(this, 0, 0);
		LHandMFinger.addBox(0F, -1F, 0F, 1, 1, 3);
		LHandMFinger.setRotationPoint(9.3F, 7.8F, 0F);
		LHandMFinger.setTextureSize(64, 32);
		LHandMFinger.mirror = true;
		setRotation(LHandMFinger, -2.443461F, 0F, 0F);
		LHandLFinger = new ModelRenderer(this, 0, 0);
		LHandLFinger.addBox(0F, -1F, 0F, 1, 1, 3);
		LHandLFinger.setRotationPoint(10F, 7.5F, 1F);
		LHandLFinger.setTextureSize(64, 32);
		LHandLFinger.mirror = true;
		setRotation(LHandLFinger, -2.443461F, -0.2617994F, 0F);
		LHandLFingerA = new ModelRenderer(this, 0, 0);
		LHandLFingerA.addBox(0F, 0F, 0F, 1, 1, 3);
		LHandLFingerA.setRotationPoint(10F, 7.5F, 1F);
		LHandLFingerA.setTextureSize(64, 32);
		LHandLFingerA.mirror = true;
		setRotation(LHandLFingerA, -2.268928F, -0.2617994F, 0F);
		LArmUppder = new ModelRenderer(this, 0, 0);
		LArmUppder.addBox(-1.5F, -1F, -1F, 2, 2, 8);
		LArmUppder.setRotationPoint(7F, -1F, 2.5F);
		LArmUppder.setTextureSize(64, 32);
		LArmUppder.mirror = true;
		setRotation(LArmUppder, -1.22173F, 0F, -0.5235988F);
		LArmLower = new ModelRenderer(this, 0, 0);
		LArmLower.addBox(-0.8F, -1F, -0.7F, 2, 2, 7);
		LArmLower.setRotationPoint(9.5F, 5F, 5F);
		LArmLower.setTextureSize(64, 32);
		LArmLower.mirror = true;
		setRotation(LArmLower, -2.617994F, 0F, 0F);
		RHandLFinger = new ModelRenderer(this, 0, 0);
		RHandLFinger.addBox(0F, -1F, 0F, 1, 1, 3);
		RHandLFinger.setRotationPoint(-9.5F, 7.5F, 1F);
		RHandLFinger.setTextureSize(64, 32);
		RHandLFinger.mirror = true;
		setRotation(RHandLFinger, -2.443461F, -0.2617994F, 0F);
		RHandLFingerA = new ModelRenderer(this, 0, 0);
		RHandLFingerA.addBox(0F, 0F, 0F, 1, 1, 3);
		RHandLFingerA.setRotationPoint(-9.5F, 7.5F, 1F);
		RHandLFingerA.setTextureSize(64, 32);
		RHandLFingerA.mirror = true;
		setRotation(RHandLFingerA, -2.268928F, -0.2617994F, 0F);
		RHandMFingerA = new ModelRenderer(this, 0, 0);
		RHandMFingerA.addBox(0F, 0F, 0F, 1, 1, 3);
		RHandMFingerA.setRotationPoint(-10.2F, 7.8F, 0F);
		RHandMFingerA.setTextureSize(64, 32);
		RHandMFingerA.mirror = true;
		setRotation(RHandMFingerA, -2.268928F, 0F, 0F);
		RHandMFinger = new ModelRenderer(this, 0, 0);
		RHandMFinger.addBox(0F, -1F, 0F, 1, 1, 3);
		RHandMFinger.setRotationPoint(-10.2F, 7.8F, 0F);
		RHandMFinger.setTextureSize(64, 32);
		RHandMFinger.mirror = true;
		setRotation(RHandMFinger, -2.443461F, 0F, 0F);
		RHandRFinger = new ModelRenderer(this, 0, 0);
		RHandRFinger.addBox(0F, -1F, 0F, 1, 1, 3);
		RHandRFinger.setRotationPoint(-11F, 7.5F, 1F);
		RHandRFinger.setTextureSize(64, 32);
		RHandRFinger.mirror = true;
		setRotation(RHandRFinger, -2.443461F, 0.2617994F, 0F);
		RHandRFingerA = new ModelRenderer(this, 0, 0);
		RHandRFingerA.addBox(0F, 0F, 0F, 1, 1, 3);
		RHandRFingerA.setRotationPoint(-11F, 7.5F, 1F);
		RHandRFingerA.setTextureSize(64, 32);
		RHandRFingerA.mirror = true;
		setRotation(RHandRFingerA, -2.268928F, 0.2617994F, 0F);
	}

	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		RFoot.render(f5);
		LFoot.render(f5);
		RFootRToe.render(f5);
		RFootLToe.render(f5);
		RFootRToeA.render(f5);
		RFootLToeA.render(f5);
		RFootMToe.render(f5);
		RFootMToeA.render(f5);
		LFootRToe.render(f5);
		LFootRToeA.render(f5);
		LFootMToe.render(f5);
		LFootMToeA.render(f5);
		LFootLToeA.render(f5);
		LFootLToe.render(f5);
		RFootA.render(f5);
		LFootA.render(f5);
		LLegLower.render(f5);
		RLegLower.render(f5);
		LLegUpper.render(f5);
		RLegUpper.render(f5);
		TorsoWaist.render(f5);
		TorsoLower.render(f5);
		RLegUpperA.render(f5);
		LLegUpperA.render(f5);
		LLegLowerA.render(f5);
		RLegLowerA.render(f5);
		Tail1.render(f5);
		Tail2.render(f5);
		Tail3.render(f5);
		Tail4.render(f5);
		TorsoMiddle.render(f5);
		TorsoUpper.render(f5);
		NeckLower.render(f5);
		BackLowerA.render(f5);
		NeckA.render(f5);
		Head.render(f5);
		UpperJawLower.render(f5);
		UpperJawUpper.render(f5);
		LowerJaw.render(f5);
		UpperJawSnout.render(f5);
		LowerJawA.render(f5);
		RShoulder.render(f5);
		Lshoulder.render(f5);
		RArmUpper.render(f5);
		RArmLower.render(f5);
		LHandRFingerA.render(f5);
		LHandRFinger.render(f5);
		LHandMFingerA.render(f5);
		LHandMFinger.render(f5);
		LHandLFinger.render(f5);
		LHandLFingerA.render(f5);
		LArmUppder.render(f5);
		LArmLower.render(f5);
		RHandLFinger.render(f5);
		RHandLFingerA.render(f5);
		RHandMFingerA.render(f5);
		RHandMFinger.render(f5);
		RHandRFinger.render(f5);
		RHandRFingerA.render(f5);
	}

	private void setRotation(ModelRenderer model, float x, float y, float z)
	{
		model.rotateAngleX = x;
		model.rotateAngleY = y;
		model.rotateAngleZ = z;
	}

	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}
